import ContactSection from "@/components/contact-section";
import HomeSection from "@/components/home-section";
import SkillsSection from "@/components/skills-section";
import Head from "next/head";
import { useRef } from "react";

export default function Home() {
  const homeRef = useRef(null);
  const projectRef = useRef(null);
  const skillsRef = useRef(null);
  const contactRef = useRef(null);
  const handleScroll = (section) => {
    section.current.scrollIntoView({ behavior: "smooth" });
  };
  return (
    <div className="page bg-black">
      <Head>
        <title>Intro to next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width-device-width, initial-scale=1" />
      </Head>
      <header className="w-full text-white absolute top-0 left-0 px-10 backdrop-blur-sm">
        <div className=" flex justify-between border-b-[1px] border-white py-5">
          <div id="logo">NJ</div>
          <nav>
            <ul className="flex gap-5 cursor-pointer">
              <li>
                <div onClick={() => handleScroll(projectRef)}>Projects</div>
              </li>
              <li>
                <div onClick={() => handleScroll(skillsRef)}>Skills</div>
              </li>
              <li>
                <div onClick={() => handleScroll(contactRef)}>Contact</div>
              </li>
            </ul>
          </nav>
        </div>
      </header>

      <HomeSection />
      <section id="projects" className="text-white" ref={projectRef}>
        Projects
      </section>
      <SkillsSection ref={skillsRef} />
      <ContactSection ref={contactRef} />
    </div>
  );
}
